#!/bin/sh

# aliases
alias bed='xrandr --output HDMI-0 --mode 4096x2160 --scale 0.5x0.5'
alias desk='xrandr --output HDMI-0 --mode 4096x2160 --scale 1x1'
alias yeet='yay -Rns'
alias PKGList='{ pacman -Qen & pacman -Qem ; } > PKGList.txt'

# ssh for kitty terminal
#if [[ $TERM == "xterm-kitty" ]]; then
#  alias ssh="kitty +kitten ssh"
#fi

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Colorize ls output (good for log files)
alias ls='ls --color=auto'

# Colorize diff output (good for log files)
alias diff='diff --color=auto'

# Colorize ip output (good for log files)
alias ip='ip -color=auto'
